export interface ReportCardPdfInput {
  school: string
  student: string
  roll: string
  rows: { subject: string; exam: string; marks: number; total: number; grade: string; gpa: number }[]
  average: number
  gpa: number
}

const escapePdf = (value: string) => value.replace(/[^\x20-\x7E]/g, '?').replace(/([\\()])/g, '\\$1')

export function createReportCardPdf(input: ReportCardPdfInput): Uint8Array {
  const lines = [
    'BT /F1 18 Tf 50 790 Td (' + escapePdf(input.school) + ') Tj',
    '0 -26 Td /F1 14 Tf (Student Report Card) Tj',
    '0 -24 Td /F1 10 Tf (Student: ' + escapePdf(input.student) + '   Roll: ' + escapePdf(input.roll || '-') + ') Tj',
    '0 -30 Td (Subject / Exam                         Marks       Grade       GPA) Tj',
    '0 -12 Td (--------------------------------------------------------------------------) Tj',
    ...input.rows.flatMap((row) => [
      `0 -18 Td (${escapePdf(`${row.subject} / ${row.exam}`.slice(0, 38).padEnd(38))} ${String(row.marks).padStart(5)}/${String(row.total).padEnd(5)} ${row.grade.padEnd(8)} ${row.gpa.toFixed(2)}) Tj`,
    ]),
    `0 -28 Td /F1 11 Tf (Average: ${input.average.toFixed(1)}%     GPA: ${input.gpa.toFixed(2)} / 5.00) Tj`,
    '0 -36 Td /F1 9 Tf (Generated by EduOS) Tj ET',
  ]
  const stream = lines.join('\n')
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${new TextEncoder().encode(stream).length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((object, index) => { offsets.push(new TextEncoder().encode(pdf).length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n` })
  const xref = new TextEncoder().encode(pdf).length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => String(offset).padStart(10, '0') + ' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return new TextEncoder().encode(pdf)
}
